image: alpine:latest

variables:
  DUMMY: 1
  #CI_DEBUG_TRACE: 1

build0:
  stage: build
  script:
    - echo "Build0"
    - echo $CI_PIPELINE_SOURCE
    
build1:
  stage: build
  rules:
  - if: '$CI_PIPELINE_SOURCE != "trigger"'
    changes:
      - Dockerfile
      - .gitlab-ci.yml
  script:
    - echo "Build1"
    - echo $CI_PIPELINE_SOURCE
