image: alpine:latest

variables:
  DUMMY: 1
  #CI_DEBUG_TRACE: 1

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  rules:
  - if: '$CI_PIPELINE_SOURCE != "trigger"'
    changes:
      - Dockerfile
      - .gitlab-ci.yml
  script:
    - echo "Do your build here"
